apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata:
  name: test-model
  namespace: default
spec:
  replicas: 1
  template:
    roles:
      - name: entry
        workerReplicas: 1
        entryTemplate:
          metadata: {}
          spec:
            containers:
              - name: entry
                image: nginx
        workerTemplate:
          metadata: {}
          spec:
            containers:
              - name: worker
                image: nginx

      - name: worker
        workerReplicas: 1
        entryTemplate:
          metadata: {}
          spec:
            containers:
              - name: entry
                image: nginx
        workerTemplate:
          metadata: {}
          spec:
            containers:
              - name: worker
                image: nginx
