apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: modelserving-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: workload.serving.volcano.sh/v1alpha1
    kind: ModelServing
    name: test-model
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: sum(rate(process_cpu_seconds_total[1m]))
        threshold: "0.01"
