apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kthena-router
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/component: kthena-router
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
